<?php

namespace ContainerNPoIurh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlayerManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\PlayerManager' shared autowired service.
     *
     * @return \App\Service\PlayerManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/PlayerManager.php';

        return $container->privates['App\\Service\\PlayerManager'] = new \App\Service\PlayerManager(($container->services['cache.app'] ?? $container->load('getCache_AppService')));
    }
}
