<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNPoIurh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNPoIurh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNPoIurh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNPoIurh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNPoIurh\App_KernelDevDebugContainer([
    'container.build_hash' => 'NPoIurh',
    'container.build_id' => '87408c2c',
    'container.build_time' => 1765366735,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNPoIurh');
