<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'create_waitroom_normal' => [[], ['_controller' => 'App\\Controller\\Controller::createNormalRoom'], [], [['text', '/waitroom/normal_game']], [], [], []],
    'create_waitroom_path' => [[], ['_controller' => 'App\\Controller\\Controller::createPathRoom'], [], [['text', '/waitroom/path_game']], [], [], []],
    'room_players' => [['id'], ['_controller' => 'App\\Controller\\Controller::roomPlayers'], [], [['text', '/players'], ['variable', '/', '[^/]++', 'id', true], ['text', '/waitroom']], [], [], []],
    'game_loop' => [[], ['_controller' => 'App\\Controller\\Controller::gameLoop'], [], [['text', '/game_loop']], [], [], []],
    'join_game' => [[], ['_controller' => 'App\\Controller\\Controller::joinGame'], [], [['text', '/join_game']], [], [], []],
    'test-neo4j' => [[], ['_controller' => 'App\\Controller\\Controller::index'], [], [['text', '/neo4j-test']], [], [], []],
    'homepage' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\Controller::createNormalRoom' => [[], ['_controller' => 'App\\Controller\\Controller::createNormalRoom'], [], [['text', '/waitroom/normal_game']], [], [], []],
    'App\Controller\Controller::createPathRoom' => [[], ['_controller' => 'App\\Controller\\Controller::createPathRoom'], [], [['text', '/waitroom/path_game']], [], [], []],
    'App\Controller\Controller::roomPlayers' => [['id'], ['_controller' => 'App\\Controller\\Controller::roomPlayers'], [], [['text', '/players'], ['variable', '/', '[^/]++', 'id', true], ['text', '/waitroom']], [], [], []],
    'App\Controller\Controller::gameLoop' => [[], ['_controller' => 'App\\Controller\\Controller::gameLoop'], [], [['text', '/game_loop']], [], [], []],
    'App\Controller\Controller::joinGame' => [[], ['_controller' => 'App\\Controller\\Controller::joinGame'], [], [['text', '/join_game']], [], [], []],
    'App\Controller\Controller::index' => [[], ['_controller' => 'App\\Controller\\Controller::index'], [], [['text', '/neo4j-test']], [], [], []],
    'App\Controller\HomeController::index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
];
