<?php

namespace ContainerQAjTcAh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Ozok6KNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.Ozok6KN' shared service.
     *
     * @return \Laudis\Neo4j\Contracts\ClientInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\Controller::index()": the $client argument is type-hinted with the non-existent class or interface: "Laudis\\Neo4j\\Contracts\\ClientInterface".');
    }
}
